#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
