#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt -y update
sudo apt -y install nginx
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error-404.html 
sudo sed -i '/root \/var\/www\/html;/a error_page 404 \/error-404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
