#!/usr/bin/env bash
# Configure web-02 to be identical to web-01

. /home/ubuntu/3-redirection

. /home/ubuntu/4-not_found_page_404

sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
