#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

sudo apt update
sudo apt-get install -y haproxy

echo "listen 4392-lb-01" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 3952-web-01 54.221.133.249:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 3954-web-02 50.19.30.90:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart

