#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
